#!/bin/sh
YUI_PATH="vendor/yuicompressor-2.4.8.jar"
JAVASCRIPTS=(
  "vendor/json3.js"
  "src/helper/dollar.js"
  "src/helper/dom.js"
  "src/helper/storage.js"
  "src/animations/Animations.js"
  "src/animations/Attack.js"
  "src/animations/Magic.js"
  "src/animations/FishSpawner.js"
  "src/animations/EvilPortrait.js"
  "src/interaction/Flash.js"
  "src/interaction/Popup.js"
  "src/interaction/Bar.js"
  "src/interaction/StatBar.js"
  "src/levels/Levels.js"
  "src/levels/LonelyIsland.js"
  "src/levels/UnderwaterShack.js"
  "src/levels/SquirrelCity.js"
  "src/levels/SquirrelCitySecondLevelHouse.js"
  "src/levels/SquirrelCityAtticLevelHouse.js"
  "src/levels/click_methods/LevelClickMethods.js"
  "src/levels/click_methods/LonelyIsland.js"
  "src/levels/click_methods/SquirrelCity.js"
  "src/levels/click_methods/SquirrelCityFirstLevelHouse.js"
  "src/levels/click_methods/SquirrelCitySecondLevelHouse.js"
  "src/levels/click_methods/SquirrelCityAtticLevelHouse.js"
  "src/statics/ExperiencePoints.js"
  "src/callbacks/ExperienceCallbacks.js"
  "src/callbacks/StatsCallbacks.js"
  "src/callbacks/LoadCallbacks.js"
  "src/Character.js"
  "src/statics/ClickAreas.js"
  "src/statics/GameData.js"
  "src/statics/SellPrices.js"
  "src/statics/Enemies.js"
  "src/statics/Weapons.js"
  "src/statics/Armors.js"
  "src/statics/Items.js"
  "src/statics/Magic.js"
  "src/Stats.js"
  "src/items/GameMap.js"
  "src/Graphic.js"
  "src/Inventory.js"
  "src/InventoryItem.js"
  "src/battle/BattleItem.js"
  "src/Player.js"
  "src/Enemy.js"
  "src/items/Item.js"
  "src/items/Weapon.js"
  "src/items/Armor.js"
  "src/battle/Rewarder.js"
  "src/battle/events/Events.js"
  "src/battle/BattleEventEngine.js"
  "src/battle/BattleControls.js"
  "src/battle/BattleInfoHeader.js"
  "src/battle/Battle.js"
  "src/battle/BattleInitializer.js"
  "src/ClickArea.js"
  "src/Level.js"
  "src/Main.js"
  "src/Controls.js"
  "src/Boot.js"
)

if [ -e application.js ]; then rm application.js; fi
if [ -e application.min.js ]; then rm application.min.js; fi
touch 'application.js'
for i in "${JAVASCRIPTS[@]}"
do
  cat $i >> application.js
done

java -jar "$YUI_PATH" application.js -o src/application.min.js
rm -f application.js
