name: Linting

on: [pull_request]

jobs:
  run_linting:
    name: Lint Javascript files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run linter
        run: npm run lint
